### PR TITLE
Add Elixir to deps

### PR DESCRIPTION
**Pull request by opnmike**
Adds Elixir so we can run Elixir-based scripts.

### CODE REVIEW

**Comment by jamsi** [comment]
@jackmarchant's back!

**Comment by opnmike** [comment]
Thanks for the second set of eyes @jackmarchant - this one was a bit controversial.

**Comment by jackmarchant** [comment]
😂 I just wanted to give my approval, even though nobody asked for it

**Comment by opnmike** [comment]
thx 🎉 :shipit:🚀 🦜

**Pull request merged**
